all: addpeer removepeer removecontent addcontent lookupcontent

addpeer: 
	g++ addpeer.cpp -o addpeer

removepeer:
	g++ removepeer.cpp -o removepeer

addcontent: 
	g++ addcontent.cpp -o addcontent

removecontent:
	g++ removecontent.cpp -o removecontent

lookupcontent:
	g++ lookupcontent.cpp -o lookupcontent

clean:
	rm addpeer removepeer removecontent addcontent lookupcontent
